---
abstract: 'set-theoretic definition of natural numbers'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Number::Natural::SetTheory
name: Number-Natural-SetTheory
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Exporter: 0
  JSON: 0
  boolean: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Number-Natural-SetTheory
  homepage: https://metacpan.org/release/Number-Natural-SetTheory
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-number-natural-settheory
version: 0.002
