---
abstract: 'set-theoretic definition of natural numbers'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::8 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Number-Natural-SetTheory
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Number::Natural::SetTheory:
    file: lib/Number/Natural/SetTheory.pm
    version: '0.004'
requires:
  Exporter: '0'
  JSON: '0'
  boolean: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Number-Natural-SetTheory/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Number-Natural-SetTheory
  homepage: https://metacpan.org/release/Number-Natural-SetTheory
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-number-natural-settheory.git
version: '0.004'
